import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SiteHeader } from "@/components/site/site-header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background` }
      >
        <SiteHeader
          siteName="Welcome"
          menu={[
            { title: "Home", url: "/" },
            { title: "More", url: "/more", children: [
              { title: "More 1", url: "/more/1" },
              { title: "More 2", url: "/more/2" },
              { title: "More 3", url: "/more/3" },
            ] },
            { title: "About", url: "/about" },
          ]}
        />
        {children}
      </body>
    </html>
  );
}
